### ISSUE TITLE
Typo in INSTALL.md instruction

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#114]
`gem install wxrbuy3 -- WXWIN=/path/to/wx/install WXXML=/path/to/wx/doxygen/xml`

should be

`gem install wxruby3 -- WXWIN=/path/to/wx/install WXXML=/path/to/wx/doxygen/xml`

Obviously not a big deal, but it's something people will presumably copy and paste only to find it doesn't work without tweaking.

**Comment by mcorino** [comment]
Right. Thanks!
Fixed it.
