### ISSUE TITLE
Example for SizerFlags is in C++

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#130]
You are probably already aware of this, but I thought I'd at least mention it in case it's an outlier that slipped through the cracks.

The documentation for Wx::SizerFlags (https://mcorino.github.io/wxRuby3/Wx/SizerFlags.html)  is still using C++ for it's example code:

```
For example, instead of

    sizer->Add(ctrl, 0, wxEXPAND | wxALL, 10);

you can now write

    sizer->Add(ctrl, wxSizerFlags().Expand().Border(wxALL, 10));
```

**Comment by mcorino** [comment]
Yep, I am aware of this.
No, it's not an outlier. There are lot's more examples in the docs that are still C++.
Automatic conversion of method specs (names, arguments, returns, types) and all sorts of type names in the text was relatively easy. Doing that with the descriptive texts and (especially)  the examples a lot less so. This required a different approach involving manual steps. It's a work in progress.
Meanwhile if you encounter a c++ example try to read:

-  `->` as `.`
- `wxABC` as `Wx::ABC`
- `AbcDef` as `abc_def`
- `new wxSomething()` or `wxSomething()` as `Wx::Something.new()`
- loose the `;`

and you'll be mostly good :smiley:
