### ISSUE TITLE
Issue with installing wxruby3 on MacOS Ventura on Intel Mac

### ISSUE THREAD

**Issue by AndyObtiva** [mcorino/wxRuby3#131]
When I run the command `gem install wxruby3 --pre`, I get a failure despite having all the prerequisites in [INSTALL.md](https://github.com/mcorino/wxRuby3/blob/master/INSTALL.md) (except for wxWidgets because I assumed it would get compiled from scratch):

```
 % gem install wxruby3 --pre
Building native extensions. This could take a while...
ERROR:  Error installing wxruby3:
	ERROR: Failed to build gem native extension.

    current directory: ~/.rvm/gems/ruby-3.1.0@glimmer-dsl-wx/gems/wxruby3-0.9.0.pre.rc.2/ext
~/.rvm/rubies/ruby-3.1.0/bin/ruby mkrf_conf_srcgem.rb
Running 'rake  configure'
ERROR: Cannot find wxWidgets. wxRuby requires a wxWidgets >= 3.2.0 release.
Failed to configure wxRuby3
Please make sure you have a valid build environment either by having a system provided wxWidgets 
development package installed (>= 3.2.0) or provide the paths to a locally built and installed 
wxWidgets release (>= 3.2.0) by setting the WXWIN environment variable (and optionally WXXML) 
for the 'gem install' command.
Installed versions of SWIG (>= 3.0.12) and (if no WXXML path is provided) doxygen and git are
also required. 
Checkout the documentation at https://github.com/mcorino/wxRuby3 for more information.

rake failed, exit code 1

Gem files will remain installed in ~/.rvm/gems/ruby-3.1.0@glimmer-dsl-wx/gems/wxruby3-0.9.0.pre.rc.2 for inspection.
Results logged to ~/.rvm/gems/ruby-3.1.0@glimmer-dsl-wx/extensions/x86_64-darwin-22/3.1.0/wxruby3-0.9.0.pre.rc.2/gem_make.out
```

If I open `gem_make.out`, I see the same error message above.

I assumed I didn't have to install wxWidgets anywhere because it would get compiled from scratch. If I am wrong, please let me know what to do to fix this issue.

**Comment by mcorino** [comment]
Good to see your system problems are solved.

No, the gem installation will not download and build an embedded wxWidgets installation by default.
Please read the [Installation of a wxRuby3 Gem](https://github.com/mcorino/wxRuby3/blob/master/INSTALL.md#installation-of-a-wxruby3-gem) section carefully. Especially the paragraph about the wxWidgets installation.
It explains the 3 options for fulfilling the wxWidgets requirement. Option 3 is probably what you need/want.

**Comment by AndyObtiva** [comment]
I am sorry for not paying attention. 

I ran this command:
` brew install wxwidgets`

And, then I was able to install the wxruby3 gem with no problem on the Mac.

<img width="400" alt="Screenshot 2023-07-19 at 8 26 32 PM" src="https://github.com/mcorino/wxRuby3/assets/23052/dcc5a4fc-4470-417e-8206-170c6234c731">


Thank you for your help. The issue is resolved, so I am closing it.
