### ISSUE TITLE
Docs sometimes refer to Wx::AUI:AuiToolBarItem as Wx::AuiToolBarItem

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#135]
First off, please indicate if you would prefer I not submit documentation problems at this point. I realize you are currently working on updating the scripts that create them, and I'm trying to limit raising issues to things where it seems at least possible that you might not be aware of it.

In the meantime, I encountered this in the Wx::AUI::AuiToolBarItem docs (https://mcorino.github.io/wxRuby3/Wx/AUI/AuiToolBarItem.html#initialize-instance_method). There are some references in the documentation to Wx::AuiToolBarItem as in:

```
#initialize(c) ⇒ AuiToolBarItem

Assigns the properties of the Wx::AUI::AuiToolBarItem “c” to this.

Parameters:

    c (Wx::AuiToolBarItem)
```

This also shows up in the main `Wx::AUI::AuiToolBar` docs as in:

```
#add_control(control, label = ('')) ⇒ Wx::AuiToolBarItem
#add_label(toolId, label = (''), width = -1)) ⇒ Wx::AuiToolBarItem
#add_separator ⇒ Wx::AuiToolBarItem
```

**Comment by AndyObtiva** [comment]
Just to share my 2 cents as an open source software author and maintainer myself, issues regarding documentation are so trivial they’re better created as pull request fixes (like my PR from the other day: https://github.com/mcorino/wxRuby3/pull/134). Open source projects are community efforts, not a one man effort. If you spot issues in the docs, that is your opportunity to make a contribution. Unless of course, you’re very confused about something and need help because you don’t have the answer/solution to the problem you spotted.

**Comment by mcorino** [comment]
However much I appreciate (and agree with) the sentiment described by @AndyObtiva  in this case I think @Randalphwa  was right in bringing this to my attention.
As he rightly remarks this part of the documentation is automatically generated by project-specific scripts which (at least at this stage of the project) are not readily grasped by anyone not immersed in the project like I am (although I would definitely appreciate anyone taking the time and effort to do so).
I did notice this issue before but it did not register as a priority issue in my brain as I felt (and still feel) that in the context of the entire documentation the meaning of what was described was clear enough.

As however my goal for the documentation is to have at least the naming (class/methods/types), method signatures and examples correctly Rubified this needs to be fixed as it has now on the master branch.

There will however surely remain inconsistencies in the generated documentation that at some point I will probably not bother to actively correct anymore. As the bulk of the summary and detail descriptions were meant for C++ code these are full of references to practices or constructs that have no meaning, are incorrect or need adaptation to work with wxRuby.
And while I have put a mechanism in place (now used to Rubify the examples) with which these texts can be updated without programming (updating the project scripts) I will not put in unlimited time and effort to fix these descriptions but rather leave these as "an exercise for the reader" :smiley: .

**Comment by AndyObtiva** [comment]
>  I think @Randalphwa was right in bringing this to my attention.

I didn't disagree about that though. If I were in your shoes, I would want him to bring it to my attention too. If he could submit a Pull Request with the fix though (like by fixing comments in the code that make it to the auto-generated documentation), that would be even better. I've had people do that in some of my projects, and I really appreciated going the extra mile on top of reporting.
