### ISSUE TITLE
Unable to create Wx::HyperlinkCtrl

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#144]
It looks like Wx::HyperlinkCtrl is missing a parent window parameter? When I try to create the control using:

```Ruby
    @hyperlink = Wx::HyperlinkCtrl.new(self, Wx::ID_ANY, 'Hyperlink',
      'https://mcorino.github.io/wxRuby3/Wx/HyperlinkCtrl.html')
```

I get:

```
Error initializing #<Wx::HyperlinkCtrl:0x0000022a94a14030 @__swigtype__="_p_wxHyperlinkCtrl"> (NameError)

Correct parameters for Wx::HyperlinkCtrl.new are:
:id => (Wx::StandardID)
:label => (String)
:url => (String)
:pos => (Wx::Point)
:size => (Wx::Size)
:style => (Integer)
:name => (String)
```

BTW, sorry I didn't get a chance to test these controls a lot earlier. I missed your Beta announcement, and since your first RC announcement, I've been scrambling to add code generation for wxRuby3 to wxUiEditor. Hence issues appearing in mostly alphabetical order as I work down the list of controls to verify valid code generation. Anyway, no rush on finding/fixing these from my perspective -- I'm noting the ones that I'm having problems with, and will check again before I release a beta for wxRuby3 support (which will probably be after you actually release).

**Comment by mcorino** [comment]
No it's not missing the parent parameter. The error is a little misleading as it never mentions the ever prevent parent parameter (I'm gonna fix that too).
Problem here was a bug in the wxWidgets interface docs incorrectly declaring this class abstract. I will add a fix for that and submit a PR for wxWidgets.
