### ISSUE TITLE
Wx::BitmapBundle.from_image() is undefined

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#147]
I'm not sure if this is an issue of the documentation, or a problem with the underlying code. The docs state that `Wx::BitmapBundle` supports `.from_image()`. However, the following code:

```Ruby
bundle = Wx::BitmapBundle.new
bundle.from_image(image)
```

results in a Ruby error:

```
accessors.rb:53:in `method_missing': undefined method `from_image' for #<Wx::BitmapBundle
```

By contrast, `bundle = Wx::BitmapBundle.new(image)` works fine, so I know the problem is not with the `image` itself (which is a Wx::Image).

**Comment by Randalphwa** [comment]
More critically, at least for wxUiEditor, is the `.from_bitmaps()` is missing which means I can't generate code for creating a bundle for multiple bitmaps as I can with the other languages it supports. I haven't tried it yet, but I'm guessing all the .from_...() functions are missing which also means no `.from_svg()`?

**Comment by mcorino** [comment]
Again a mixup of class and instances, this time the other way around. :wink: 
These `from_XXX` methods are **class** methods.
Try:
```ruby
bundle = Wx::BitmapBundle.from_image(image)
```

**Comment by mcorino** [comment]
> The _joys_ of trying to speed-learn a new programming language... 😢
> 

I find that making mistakes this way helps fix the right in your mind after solving it. :wink: 

> I've fixed two out of the three bundle cases that I'm generating, but I'm stuck on trying to pass an array of bitmaps. I'm using:
> 
> ```ruby
>         bitmaps = [Wx::Bitmap.new(image1),
>                    Wx::Bitmap.new(image2),
>                    Wx::Bitmap.new(image3)]
>         bundle = Wx::BitmapBundle.from_bitmaps(bitmaps)
> ```
> 
> That gives me:
> 
> ```
> from_bitmaps': Wrong arguments for overloaded method 'wxBitmapBundle.FromBitmaps'. (ArgumentError)
> Possible C/C++ prototypes are:
>     wxBitmapBundle wxBitmapBundle.FromBitmaps(wxVector< wxBitmap > const &bitmaps)
>     wxBitmapBundle wxBitmapBundle.FromBitmaps(wxBitmap const &bitmap1, wxBitmap const &bitmap2)
> ```
> 
> I tried creating an empty array and pushing the bitmaps into, but same error. In this case, I'm reasonably certain my syntax is right since the code
> 
> ```ruby
>         bundle = Wx::BitmapBundle.from_bitmaps(Wx::Bitmap.new(image1),
>                                                Wx::Bitmap.new(image2))
> ```
> 
> works just fine. But I'm stumped on how to get `from_bitmaps` to take an Array and pass it to wxBitmapBundle as a wxVector.

You can't. That something wxRuby should take care of for you.
Congrats, you found another remaining omission. :clap: 
After I fix this your array code above should definitely work.

**Comment by Randalphwa** [comment]
wxUiEditor generates code for roughly 140 wxWidgets UI classes for C++, wxPython and now wxRuby. I've generated and run around 120 of those for wxRuby -- minus 11 that are not implemented in wxRuby. One of those is wxWrapSizer which you already know about. None of the missing ones other than wxWrapSizer are critical from wxUiEditor's perspective -- I can simply warn the user if they try to add an unsupported control which I already do for wxPython. I was planning on adding an issue here just listing the controls in case you weren't aware of them. However, I also know you are planning on a final release next month, and I don't want to pop them on you so late that you can't do anything about them even if you wanted to. It's likely to be well into next week before I complete verifying every control that I can potentially generate for wxRuby -- so the question is, would you prefer the partial list now, or just get a complete list when I've completed the wxUiEditor support?

**Comment by mcorino** [comment]
Just give me what you have now. 
A lot of widgets do not take a lot of time to add anymore.
I can always add the more difficult ones to a todo list.

**Comment by mcorino** [comment]
Preferably in a new issue as this one is going to close after I merge the latest PR.
