### ISSUE TITLE
Error on Windows trying to set RibbonBar.set_art_provider

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#149]
I'm getting an error for any value I use for `set_art_provider` which I suspect is Windows-specific. I have the following code:

```Ruby
    @rbnBar = Wx::RBN::RibbonBar.new(page, Wx::ID_ANY, Wx::DEFAULT_POSITION,
      Wx::DEFAULT_SIZE, Wx::RBN::RIBBON_BAR_SHOW_PAGE_LABELS|
      Wx::RBN::RIBBON_BAR_SHOW_PAGE_ICONS|Wx::RBN::RIBBON_BAR_FLOW_HORIZONTAL)

    @rbnBar.set_art_provider(Wx::RibbonDefaultArtProvider)
```

What I get is:

```
 `set_art_provider': Expected argument 1 of type wxRibbonArtProvider *, but got Class
         Wx::RBN::RibbonMSWArtProvider (TypeError)
        in SWIG method 'SetArtProvider'

    @rbnBar.set_art_provider(Wx::RBN::RibbonDefaultArtProvider)
```

I have tried both variants: Wx::RBN::RibbonAUIArtProvider and Wx::RBN::RibbonMSWArtProvider  -- both of them generate an error.

**Comment by mcorino** [comment]
It would seem to me the error message is clear enough :wink: : 
```
set_art_provider': Expected argument 1 of type wxRibbonArtProvider *, but got Class
         Wx::RBN::RibbonMSWArtProvider (TypeError)
        in SWIG method 'SetArtProvider'

    @rbnBar.set_art_provider(Wx::RBN::RibbonDefaultArtProvider)
```

`set_art_provider` expects an `Wx::RBN::RibbonArtProvider` **INSTANCE** and you are passing it a **class**.
Just add `.new` and you should be good.

**Comment by Randalphwa** [comment]
Ack! On the bright side, it's a simple fix on my part without adding more to your workload.
