### ISSUE TITLE
Constructor docs for the Wx::Scrolled variants doesn't show actual ctor name

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#169]
The documentation for `Wx::ScrolledWindow`, `Wx::ScrolledCanvas` and `Wx::ScrolledControl` all list the constructor as "#initialize ⇒ Wx::Scrolled" rather than the actual constructor (`Wx::ScrolledWindow`, etc.). I'm not sure if that's by design or just the algorithm getting thrown off by the wxWidgets version of `wxScroledl<wxPanel>`.

**Comment by mcorino** [comment]
Ah yes, these pesky template mappings. :wink: 
Fix coming up.

**Comment by mcorino** [comment]
Fixed by #170
