### ISSUE TITLE
wxGetStockLabel() not ported to wxRuby

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#197]
It looks like `wxGetStockLabel` in `stockitem.h` has not been ported to wxRuby. This function can be helpful for menu items to provide a consistent label and accelerator.

**Comment by mcorino** [comment]
wxGetStockLabel is ported, as is wxGetStockAccelerator, wxGetStockHelpLabel and others.
Look for Wx.get_stock_label in the documentation.
Remember that all method/function names will be rubified and global functions will be wrapped as module methods.
