### ISSUE TITLE
Code error messages

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#198]
Prior to 0.9.0, if you ran ruby from a Windows command prompt, and there was a fatal error caused by an error in the user's ruby code, the error log information would be written to the command prompt window (presumably to stdout or stderr). With 0.9.0, the error information is instead displayed in a dialog box, without the ability to copy the text of the error message. That makes fixing the problem harder, since you cannot see the error message and your code at the same time.

My question is whether there is any way for the user to either a) have that text copy-able, or written to a log file, or b) turned off so that the error text is written to stdout or stderr?

**Comment by Randalphwa** [comment]
Erg, now I'm seeing it both ways -- it seems to depend on what the error is. A syntax error, such as an extra trailing parenthesis goes to the shell, a missing function goes to the dialog. Ruby error versus wxWidgets error? Still wish they _all_ went to the shell...

**Comment by mcorino** [comment]
The GUI code was inserted to plug a hole and I'm not really pleased with it either. I'm working on a better exception handling solution though which will fix that and bring proper exception propagation Ruby-style.

**Comment by mcorino** [comment]
This has been fixed/addressed in the v0.9.1 release.
