### ISSUE TITLE
Missing wxFileCtrl port?

### ISSUE THREAD

**Issue by Randalphwa** [mcorino/wxRuby3#204]
It looks like wxFileCtrl (https://docs.wxwidgets.org/3.2.0/classwx_file_ctrl.html) did not get ported. Or at least it isn't documented, and trying to use it (`Wx::FileCtrl.new`) results in `uninitialized constant Wx::FileCtrl`.

**Comment by mcorino** [comment]
Yep, this one is missing. There are simply too many widgets in wxWidgets :wink: 
Thanks for noticing. I'll put it on the todo list.
