### ISSUE TITLE
[Documentation] Windows support, 101 - describing the steps needed to make wxRuby3 work on the windows platform

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#222]
Hey there mcorino,

Could you show, or link to, instructions how to use wxRuby3 on windows?

This may help people choose between, for instance, libui-ng (and the bindings
kojix2 maintains) and wxRuby3.

Specifically what I would like to suggest this documentation should include
are:

1) From a vanilla windows machine, say Win10, what do we have to download?
(I assume ruby, wxRuby3 but also wxwidgets I suppose - perhaps you can
mention these specifically and where they can be found.)

2) Once these were all downloaded and installed, how to get towards a 
"hello world" example? That is, which file to specifically invoke to show
that this all works?

I think that's it.

The reason why I would like to request this is so that we instantly know
that it works on windows; and how to start. Once it all works well, 
people can learn things on their own.

I am mostly using Linux myself, but my use case would be to make it
work on windows, because of elderly relatives who use Windows, so 
I want to have them use a GUI. Right now my choices are libui-ng,
and java-SWING (via jruby). Adding wxRuby3 to this would be nice to
have. Right now I don't know if this is possible (I also invested too
little time into wxwidgets in general, which is another reason why I
think having this documented is useful; you already mention that it
works on windows, so my request here is more like a request to 
extend this information specifically, e. g. "The steps necessary to
make it work on windows").

At any rate, as always, please feel free to go about this request in
any way you see fit, including closing it at any moment in time
at your leisure. Thanks for reading!

**Comment by mcorino** [comment]
Please describe in detail what information you think is missing from the https://github.com/mcorino/wxRuby3/blob/master/INSTALL.md document (preferably including suggestions for improvement) especially regarding this section:

> On Windows systems a prebuilt binary gem is available for the latest stable release(s) of [RubyInstaller](https://rubyinstaller.org/) installed rubies that will be installed by default if installing for that platform (including an embedded, latest stable version, wxWidgets installation).

As far as 'Hello world!' is concerned the same applies to the https://github.com/mcorino/wxRuby3/blob/master/lib/wx/doc/extra/00_starting.md document.

**Comment by mcorino** [comment]
No feedback, so considering this solved.
