### ISSUE TITLE
a change for pressing enter on unavailable "grade out" context menu options

### ISSUE THREAD

**Issue by HanaDadfar** [mcorino/wxRuby3#283]
### Description
hi.
I reported and wel explaned what is needed hear, it was the incorrect place for it, so people helpped me to be directed hear, because the problem is related to keyboard pressing event
https://github.com/nvaccess/nvda/issues/16638
thanks, i really hope that this gets implemented soon, as nvda and all it's addons are using wx, and this is the correct action for the grade out menu options, which qt already does this, read the complete discription on the link provided above
Thanks

**Comment by mcorino** [comment]
This is not the wxWidgets repository. See https://github.com/wxWidgets/wxWidgets
