### ISSUE TITLE
Is it possible use Wx::HtmlWindow with css style classes or maybe bootstrap?

### ISSUE THREAD

**Issue by lcuevastodoit** [mcorino/wxRuby3#288]
Hi, excellent work, Just me asking
Is it possible use Wx::HtmlWindow with css style classes or maybe bootstrap?
right now I am developing with wxruby3-1.0.1 on macos
all working great so far
but css styles not working over Wx::HtmlWindow
only old html style attributes supported until now
also I did note wx/webview is not available

Regards

Luis

**Comment by mcorino** [comment]
Wx::HtmlWindow supports everything that wxWidgets wxHtmlWindow supports which is a (large) subset of HTML and a minimum of styles (no CSS stylesheets). See the wxWidgets wxHTML overview doc for more details.I have not (yet) wrapped wxWebView and have no immediate plans to do so myself.On 20 Jun 2024 05:04, LUIS CUEVAS ***@***.***> wrote:
Hi, excellent work, Just me asking
Is it possible use Wx::HtmlWindow with css style classes or maybe bootstrap?
right now I am developing with wxruby3-1.0.1 on macos
all working great so far
but css styles not working over Wx::HtmlWindow
only old html style attributes supported until now
also I did note wx/webview is not available
Regards
Luis

**Comment by lcuevastodoit** [comment]
@mcorino If you agree, in a fork I will try to wrap WxWebView, I will keep you posted
It may take a while, I'll do it in my free time.
Thanks for answering

**Comment by mcorino** [comment]
PRs with enhancements are always welcome.Take your time. Better late and correct than fast and faulty.On 4 Jul 2024 23:26, LUIS CUEVAS ***@***.***> wrote:
@mcorino If you agree, in a fork I will try to wrap WxWebView, I will keep you posted
It may take a while, I'll do it in my free time.
Thanks for answering
