### ISSUE TITLE
EVT_HOTKEY(hotkeyId, fnc) not implemented

### ISSUE THREAD

**Issue by Youngv** [mcorino/wxRuby3#312]
### Description

I want to capture global hotkey events when the application is running in the background. However, the code I have only works when the application is in the foreground. I noticed that the wiki section regarding this is still a work in progress: [Catching Key Events Globally](https://github.com/mcorino/wxRuby3/wiki/HowTo-%3A-Catching-key-events-globally).

I am using Windows 11 and found the documentation for the `register_hot_key` method here: [#register_hot_key(hotkeyId, modifiers, virtualKeyCode)](https://mcorino.github.io/wxRuby3/Wx/Window.html#register_hot_key-instance_method). However, I cannot find the documentation for `EVT_HOTKEY(hotkeyId, fnc)`. 

Could you please help me with this? Thank you!

```ruby
require 'wx'

class TheFrame < Wx::Frame
  def initialize(title)
    super(nil, title: title)
    panel = Wx::Panel.new(self)
    button = Wx::Button.new(panel, label: 'Click me')
    button.evt_button(Wx::ID_ANY) { Wx.message_box('Hello. Thanks for clicking me!', 'Hello Button sample') }

    accel_entries = [
      Wx::AcceleratorEntry.new(Wx::ACCEL_CTRL, 'H'.ord, 1001)
    ]
    set_accelerator_table(Wx::AcceleratorTable.new(accel_entries))
    evt_menu(1001) { on_hotkey_pressed }
  end

  def on_hotkey_pressed
    Wx.message_box('Ctrl+H pressed！', 'Notice', Wx::OK | Wx::ICON_INFORMATION)
  end

  def key_down(event)
    puts "1"
    event
  end
end

Wx::App.run { TheFrame.new('Hello world!').show }
```

**Comment by mcorino** [comment]
Yes, you are right. The #evt_hotkey connector method is missing.
This is another one of the 'special cases' in the wxWidgets docs that I did not catch yet.
I'm updating the code for the coming 1.3.0 release (coming week).

In the mean time you could patch the Ruby code of your 1.2.1 wxRuby3 gem if you want (there should not be any changes to the native extension library involved).
To do that do the following:

1. add the following code just before the closing `end` in the `lib/wx/core/event.rb`  file (right after the `evt_nc_paint` definition):
```ruby
  if Wx.const_defined?(:EVT_HOTKEY)
    EvtHandler.register_event_type EvtHandler::EventType[
                                     'evt_hotkey', 1,
                                     Wx::EVT_HOTKEY,
                                     Wx::KeyEvent
                                   ]
  end
```
2. add the following documentation to the `lib/wx/doc/evthandler.rb` (right after the documentation for `call_after`):
```ruby

    # Process a {Wx::EVT_HOTKEY} event.
    # @param [Integer] id hotkey id
    # @param [String,Symbol,Method,Proc] meth (name of) method or handler proc
    # @yieldparam [Wx::KeyEvent] event the event to handle
    def evt_hotkey(id, meth = nil, &block) end
```

**Comment by Youngv** [comment]
Thank you so much for your help! The solution worked perfectly.
