### ISSUE TITLE
About "wxruby setup"

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#329]
Today I was trying the above command, shown on the next line:

    wxruby setup

for the first time on my linux machine.

First, it is quite convenient that you provide a wxruby executable. I may have missed
this in the past, not sure.

I wanted to see which version I am using:

    wxruby --version

It told me:

    wxruby: version unknown

I would highly recommend adding --version here; I think this may simplify user feedback
in the future. This is just an aside, though, so back to "wxruby setup".

The output it shows to me is the following:

    ---            
    Now running wxRuby3 post-install setup.
    This will (possibly) install required software, build the wxWidgets libraries (if needed), 
    build the native wxRuby3 extensions and generate the wxRuby3 reference documentation.
    Please be patient as this may take quite a while depending on your system.
    ---

    Checking out wxWidgets...done!
    Building wxRuby3 extensions...|

It is a good idea to inform the user what will happen.

I do like verbose output, though. If information is already obtained, then perhaps you could
add "wxruby setup --verbose" or something like that, and briefly mention this on the user's
terminal, such as "For more extensive output, consider using `wxruby setup --verbose`" or
something like that. I have no problem with this doing automatic things, but still I'd like to
see what it is doing, so I can understand what is going on. Right now it is a bit of a blackbox
to me. For instance, it fetches the sources from which remote computer? I think being able
to show this information, if the user wants it, may be useful.

For instance:

    Checking out wxWidgets...done!

Right now I have no idea what it did here. I assume it downloaded something, but at the least
in a verbose manner I'd like to know what it downloaded; and where I can find the downloaded
data.

The next small thing: right now I don't know how long it takes. Perhaps you can give some estimate
on the commandline, e. g. "it typically takes 4-8 minutes on a modern computer" or something like
that. Does not have to be super-exact, can be in () parens - just a brief notification how long it may
take. Compare the LFS/BLFS SBU units: https://www.linuxfromscratch.org/~bdubbs/about.html this
is also not super-informative, but as a rough estimate, SBU can be useful. (For me I just like the number
of minutes; this is easiest for my brain to digest.)

Anyway, I tested it; the samples show up and I can view the source. \o/

Will take me a while to work through the samples. (By the way, it would be nice if the samples dialogue has an option for larger font sizes - that may help elderly people like me. :D)

**Comment by mcorino** [comment]
> I wanted to see which version I am using:
> 
> ```
> wxruby --version
> ```
> 
> It told me:
> 
> ```
> wxruby: version unknown
> ```
> 

This might be a good idea. I will add it to the list for the next release.

> It is a good idea to inform the user what will happen.
> 
> I do like verbose output, though. If information is already obtained, then perhaps you could add "wxruby setup --verbose" or something like that, and briefly mention this on the user's terminal, such as "For more extensive output, consider using `wxruby setup --verbose`" or something like that. I have no problem with this doing automatic things, but still I'd like to see what it is doing, so I can understand what is going on. Right now it is a bit of a blackbox to me. For instance, it fetches the sources from which remote computer? I think being able to show this information, if the user wants it, may be useful.
> 
> For instance:
> 
> ```
> Checking out wxWidgets...done!
> ```
> 
> Right now I have no idea what it did here. I assume it downloaded something, but at the least in a verbose manner I'd like to know what it downloaded; and where I can find the downloaded data.
> 

That information is mostly of interest for people (assisting in) developing wxRuby3.
Printing information for the average user would only provide a false sense of security because the tool could print whatever it wanted you to see and still do something else entirely.

If you are really concerned about what it might do you could:

1.  inspect the code (the GREAT thing about open source software is the public availability of all source code and for Ruby the advantage is double as even the installed software will allow you to inspect the source in this case);
2. run `wxruby setup --log $(pwd)` (see remark above about 'false security'); if you want even more output you could run `WXRUBY_VERBOSE=1 wxruby setup --log $(pwd)`.

> The next small thing: right now I don't know how long it takes. Perhaps you can give some estimate on the commandline, e. g. "it typically takes 4-8 minutes on a modern computer" or something like that. Does not have to be super-exact, can be in () parens - just a brief notification how long it may take. Compare the LFS/BLFS SBU units: https://www.linuxfromscratch.org/~bdubbs/about.html this is also not super-informative, but as a rough estimate, SBU can be useful. (For me I just like the number of minutes; this is easiest for my brain to digest.)
> 

I will see what I can do. But most likely this will be something in the order of 'Be patient, sit back and relax, this will take quite a while on any computer'

> 
> Will take me a while to work through the samples. (By the way, it would be nice if the samples dialogue has an option for larger font sizes - that may help elderly people like me. :D)

I prefer to leave that to the system settings (at least for these sample apps). All platform have settings to globally enlarge anything displayed.

**Comment by mcorino** [comment]
The '--version' switch will be added in the next release.
