### ISSUE TITLE
Coding style, e. g. shorter hash

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#330]
So I am now learning wxruby. I am a slow learner so this will take me
some time. I plan to showcase a few things with it, though, as I already
learned ruby-gtk3 before, and I know HTML/CSS fairly well, so I think
I should make progress soon. Anyway.

I noticed ruby code such as in:

    wxRuby3/samples/minimal/ruby minimal.rb 

You use:

    super(nil, :title => title, :size => [ 400, 300 ])

Of course that is perfectly valid ruby code.

However had, for symbol-keys, we could also use this shorter notation:
  
    super(nil, title: title, size: [ 400, 300 ])

It is not a huge savings, though, only about 6 characters or so. But I still wanted to suggest
it even if you disagree with it. I like the shortcut notation because it is a bit more convenient,
which is nice in the long run when you have to write a LOT of ruby code.

**Comment by mcorino** [comment]
Although I value feedback, these things are simply matters of taste without any performance or functional consequences and as such I would suggest that if such things seem important enough for you, you submit PR's for changing this (and other) code.
