### ISSUE TITLE
wxruby and warnings?

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#331]
I typically run all my local .rb files with the -w flag, such as via:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true

However had doing so leads to this craziness:

    /root/.gem/gems/wxruby3-1.3.1/lib/wxruby_core.so: warning: method redefined; discarding old get_active_window
    /root/.gem/gems/wxruby3-1.3.1/lib/wxruby_core.so: warning: method redefined; discarding old get_active_window
    /root/.gem/gems/wxruby3-1.3.1/lib/wxruby_core.so: warning: method redefined; discarding old generic_about_box
    /root/.gem/gems/wxruby3-1.3.1/lib/wxruby_core.so: warning: method redefined; discarding old generic_about_box
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/evthandler.rb:64: warning: method redefined; discarding old add_filter
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/evthandler.rb:70: warning: method redefined; discarding old remove_filter
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/evthandler.rb:225: warning: method redefined; discarding old call_after
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/acceleratortable.rb:19: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/animation.rb:16: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/app.rb:98: warning: method redefined; discarding old on_assert_failure
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/artprovider.rb:17: warning: method redefined; discarding old push_back
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/artprovider.rb:23: warning: method redefined; discarding old pop
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/artprovider.rb:29: warning: method redefined; discarding old push
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/artprovider.rb:35: warning: method redefined; discarding old delete
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/bitmap.rb:81: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/bitmap_combobox.rb:14: warning: method redefined; discarding old append
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/bitmap_combobox.rb:25: warning: method redefined; discarding old insert
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/clipboard.rb:32: warning: mismatched indentations at 'ensure' with 'def' at 18
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/clipboard.rb:44: warning: method redefined; discarding old add_data
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/clipboard.rb:50: warning: method redefined; discarding old clear
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/colour.rb:20: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/colour.rb:34: warning: method redefined; discarding old ==
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/controlwithitems.rb:48: warning: method redefined; discarding old each_string
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:45: warning: method redefined; discarding old for_path
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:67: warning: method redefined; discarding old each_entry
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:76: warning: method redefined; discarding old each_group
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:86: warning: method redefined; discarding old path
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:92: warning: method redefined; discarding old rename
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:99: warning: method redefined; discarding old number_of_entries
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/config.rb:108: warning: method redefined; discarding old number_of_groups
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/data_object.rb:69: warning: method redefined; discarding old _get_data_size
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/dataformat.rb:13: warning: method redefined; discarding old ==
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/dialog.rb:17: warning: assigned but unused variable - prev_adapter
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/dialog.rb:16: warning: method redefined; discarding old set_layout_adapter
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/event.rb:19: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/event.rb:37: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/find_replace_dialog.rb:18: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/find_replace_dialog.rb:24: warning: method redefined; discarding old set_data
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/functions.rb:16: warning: method redefined; discarding old about_box
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/geometry.rb:26: warning: method redefined; discarding old assign
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/geometry.rb:79: warning: method redefined; discarding old assign
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/graphics_pen_info.rb:13: warning: method redefined; discarding old dashes
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/simplehelpprovider.rb:44: warning: assigned but unused variable - tip
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/helpprovider.rb:19: warning: method redefined; discarding old set
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/icon.rb:47: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/image.rb:61: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/image.rb:106: warning: method redefined; discarding old compute_histogram
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/imagelist.rb:13: warning: method redefined; discarding old add
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:15: warning: method redefined; discarding old get_system_encoding_name
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:35: warning: method redefined; discarding old is_available
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:40: warning: method redefined; discarding old get_language_info
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:45: warning: method redefined; discarding old get_language_name
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:50: warning: method redefined; discarding old get_language_canonical_name
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/locale.rb:69: warning: method redefined; discarding old init
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:51: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:103: warning: method redefined; discarding old log_generic
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:108: warning: method redefined; discarding old log_info
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:113: warning: method redefined; discarding old log_verbose
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:118: warning: method redefined; discarding old log_message
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:123: warning: method redefined; discarding old log_warning
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/log.rb:128: warning: method redefined; discarding old log_error
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:31: warning: method redefined; discarding old each_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old append
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old prepend
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old append_check_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old prepend_check_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old append_radio_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:59: warning: method redefined; discarding old prepend_radio_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:82: warning: method redefined; discarding old insert
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:82: warning: method redefined; discarding old insert_check_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/menu.rb:82: warning: method redefined; discarding old insert_radio_item
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/owner_drawn_combobox.rb:35: warning: method redefined; discarding old each_string
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/pen_info.rb:13: warning: method redefined; discarding old dashes
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/persistence_manager.rb:25: warning: method redefined; discarding old get
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/persistence_manager.rb:30: warning: method redefined; discarding old set
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/rect.rb:64: warning: method redefined; discarding old offset
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/secret_store.rb:22: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/sizer.rb:55: warning: method redefined; discarding old each_child
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/sizer.rb:68: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/sizer.rb:87: warning: method redefined; discarding old initialize
    /root/.gem/gems/wxruby3-1.3.1/lib/wx/core/sizer.rb:106: warning: method redefined; discarding old initialize

And about 100 more.

Are these warnings necessary? I can re-assign $VERBOSE so I don't see any warnings, but if I run ruby-gtk3 I rarely get any warnings. Do you think the number of warnings could be reduced? It is strange that so many methods are redefined. That looks odd to me. Is some kind of special loader used here that triggers those re-definitions?

Ultimately it is not so important because the ruby code runs, and I got wxruby examples to run too \o/ but they are distracting a little bit.

**Comment by mcorino** [comment]
The redefinition are necessary. If you want to know more I suggest you check the source code.

I will look into some cleanup to prevent the warnings from appearing.

**Comment by mcorino** [comment]
This will be resolved in the next release.
