### ISSUE TITLE
[Question - or Feature] Button widget can not be standalone?

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#333]
So this works:

    button = Wx::Button.new(panel, label: 'Click me')

This does not:

    button = Wx::Button.new(label: 'Click me')
    panel.add(button)

where panel is:

    panel = Wx::Panel.new(self)

There is no method .add().

I guess this is due to how wxwidgets is designed. Hmm.

I suppose this can not be changed?

From ruby-gtk3 I am used to first create a button, and then
adding it via .add() or .minimum() or something like that to
a larger container.

The reason I like .add is because I am mostly using an 
abstract way to build up GUIs, and here it is more convenient
to first create all the small widgets before putting them together.

Whereas, if I need to create AND attach them at creation-time,
I need to come up with another way to handle that.

I can use an agnostic module with Button.new and then replace
all of that lateron, e. g. if using gtk, I use it to replace it with
a button in gtk, in wxwruby3 I use it to replace it with a Wx::Button
and so forth. But I also thought I should ask here, because perhaps
there may be some way to do that. That is, to create the widgets
WITHOUT forcing them into some container at creation-time. More
flexibility may be useful here IMO. Do the wxwidgets guys explain
this? Because to me it seems inferior to the situation of creating 
widgets WITHOUT having to attach them to a container widget at
creation time.

(Meanwhile I solved this in the module that I use to handle 
wxruby by automatically creating a @panel and passing that
to create_button(), so it is not a big issue to me. So I am mostly
just curious now why wxiwdgets chose that approach.)

**Comment by mcorino** [comment]
wxRuby3 first and foremost provides wrapping of the wxWidgets API (with rubification of class and method names) with some added Ruby-style solutions like enumerators.

wxRuby3 **WILL NOT** deviate structurally from the wxWidgets API. I leave that to add-on/related projects like [Glimmer DSL for WX](https://github.com/AndyObtiva/glimmer-dsl-wx).
