### ISSUE TITLE
Question about handling GC and same object in Ruby

### ISSUE THREAD

**Issue by Hanmac** [mcorino/wxRuby3#91]
hi i'm the developer of https://github.com/Hanmac/rwx

Recently i saw a post about your repo on the ruby mailing list so i wanted to check it out.

from the different style to wrap the binding, i myself preferred to write the functions manually so can control the data flow better
I preferred to write C++ code than Swig code.
or some other tweaks like the WX_IDs are Ruby Symbols in my version.

for example how does your version handle the connection between wxWindow and Ruby Window? And also the GC? https://mcorino.github.io/wxRuby3/file.02_lifecycles.html

how do you keep the wxWindow/Ruby object alive?

or when you create a Ruby Window and add it to a wxWindow as a child, how do you keep the reference, that when wxWindow returns your object in as an result of a function, how do you get the right Ruby Window back? the same Instance you created before?

**Comment by mcorino** [comment]
I definitely did not fancy writing all binding code manually and I was quite taken with the approach of the Phoenix (wxPython) project so I decided to try to emulate that without resorting to writing a custom code generator but rather extract the API specs from the wxWidgets doxygen generated XML interface docs and generate SWIG interface definitions from that and than use SWIG to generate the binding code. I know SWIG produces quite some overhead but it definitely beats manually coding (and maintaining!!) the bindings and I am not that concerned with footprint issues for this project. Once things stabilize I think I can shave of quite a chunk by converting a large part of the common SWIG runtime code into a shared library but I'm in no great hurry there.

I also definitely did want to rubify the interface but mostly with respect to naming and argument/result passing issues. I did *not* want to stray too far from the wxWidgets API feel by making ID's be Symbols in wxRuby3 (no offense meant). I actually went somewhat in the opposite direction by introducing the Wx::Enum class to be able to represent  wxWidgets C++ enums  with more or less the same feel and type safety.

As far as handling the connection between wxWidgets objects and Ruby objects wxRuby3 more or less relies on the standard SWIG way of doing that (wxRuby3 implements some optimizations here and there but does not change that in essence).  The SWIG way of making sure the same Ruby object once created and 'linked' to a C++ object is returned after passing through the wrapping layer is to 'track' such objects maintaining hash tables with VALUE:C++ pointer pairs and looking up the Ruby VALUE by the C++ pointer value when needed. Properly implemented the overhead is unnoticeable in normal applications.
Keeping the Ruby objects alive requires inserting the right GC marking functions with the necessary customization to cater to the specific needs of the wxWidgets life cycles (which differ for different groups of objects, windows only being one of those).

One of the benefits I get of using the 'doxygen -> XML -> SWIG -> C++ code' route is that with some simple additions I also could add the 'doxygen -> XML -> YARD docs' route which gives me pretty complete API documentation for very little effort. :smile:

**Comment by Hanmac** [comment]
one thing i used for rwx is that i learned that wxWindow (and other objects inheriting from wxEvtHandler or similar) can have a `setClientObject` inheriting from `wxClientData` which the window takes **ownership** of.

so the moment the wxWindow dies, the wxClientData object gets deleted.

i _abused_ this system as some kind of ref counter for my Ruby Object that i created from the wxWindow
as long as the Ruby Object is inside a wxClientData, i can tell the Ruby GC to keep the ruby object alive.
the moment the wxClientData gets deleted, the ruby object is freed from that protection and the GC can do its work and delete that Ruby object too.

with this the Ruby object lives for as long as needed, but not longer than necessary

**Comment by mcorino** [comment]
That's something I use too in some places but not for window objects. Those are kept alive running of the GC marker for the global App object by iterating to the list of tracked objects and removed from that list by an event handler of the App object for the destroy event. Works like a charm (except for the exceptions ... there are always exception :weary: ).
In wxRuby3 Ruby objects also are kept alive only as long as needed.

**Comment by rubyFeedback** [comment]
> I also definitely did want to rubify the interface

This is an issue I had with the ruby-gtk3 code. I felt that it emulates the C code 
too much 1:1, whereas ruby allows us to write more elegant code. For instance,
in ruby-gtk3 you kind of use this pattern:

    button.signal_connect(:clicked) {|widget, event|
    }

I simplified that to:

    button.on_clicked {|widget, event|
    }

kind of. (I have not modified the gem I use here called gtk_paradise that much though in the last
2 or 3 years.)

In the long run it would be kind of cool if we could have unified UIs similar to what Andy is doing
with glimmer. I guess if wxruby3 remains somewhat active perhaps Andy may eventually have a
look and offer support via glimmer too, just as he does with ruby-tk. Right now I do not know how 
well wxruby3 works. I usually first dig into examples and tutorials - not sure how well these are
available for wxruby3, but enough about me digressing the topic here.

**Comment by mcorino** [comment]
wxRuby3 rubifies this pretty much the same way (but than matching wxWidgets).

```ruby
  evt_button BUTTON_ID { |event| ... }
```

or 

```ruby
  evt_button BUTTON_ID, :event_handler_method
```

**Comment by mcorino** [comment]
> 
> In the long run it would be kind of cool if we could have unified UIs similar to what Andy is doing with glimmer. I guess if wxruby3 remains somewhat active perhaps Andy may eventually have a look and offer support via glimmer too, just as he does with ruby-tk. 

This is not really a priority for me. Though I admire Andy's work on Glimmer and would welcome him (or somebody else) integrating wxRuby3 there I am pretty happy with the wxRuby3 API as it is. It suits my purposes and immediate needs.

> Right now I do not know how well wxruby3 works. I usually first dig into examples and tutorials - not sure how well these are available for wxruby3, but enough about me digressing the topic here.

You won't know until you try it. :wink:
