### ISSUE TITLE
FAQ entry - differences to Hanmac's old wxruby project

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#93]
Hey there,

I just discovered the project here.

I remember many years ago hanmac wrote some wxruby bindings.

Is this project related to hanmac's work or completely independent?

Also I think some kind of FAQ, on the main README, a separate text
file or the wiki, may be useful. Many people may probably not be
aware that wxruby3 exists. I only found it just accidentally right
now when I looked at the mailing list.

**Comment by mcorino** [comment]
As described in the README this project is related to the original wxRuby & wxRuby2 projects.
This project has no relation whatsoever with hanmac's work.

There already is a FAQ on the main README.
