### ISSUE TITLE
[Documentation] Please consider specifying in the main README clearly which version of wxwidgets are supported

### ISSUE THREAD

**Issue by rubyFeedback** [mcorino/wxRuby3#94]
It would be useful to clearly state which versions of wxwidgets are supported.

I'll compile wxWidgets 3.2.2.1 soon and then I will install the latest wxRuby3, but
right now I do not know whether that works. This is why I think it would be very
useful if wxRuby3 could on the main README clearly state which version of
wxwidgets are supported. That way people quickly know whether they should
give the latest wxwidgets a try or stay to some more "stable" variant instead.

Please consider this documentation-request. Thank you for reading.

(PS: If I have missed it perhaps it could be made more prominent, like a
markdown table or something. Right now I do not know if and which
version scheme wxruby3 follows.)

**Comment by mcorino** [comment]
The first item of the FAQ on the main README pretty clearly states which platforms (OS and wxWidgets versions) are currently supported.
